import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, ExternalLink, Github } from 'lucide-react';
import { projects } from '../mock';
import { Badge } from './ui/badge';

export default function Projects() {
  const [activeFilter, setActiveFilter] = useState('All');
  const [showAll, setShowAll] = useState(false);
  const categories = ['All', ...new Set(projects.map((project) => project.category))];
  const filtered = activeFilter === 'All' ? projects : projects.filter((project) => project.category === activeFilter);
  const visible = showAll ? filtered : filtered.slice(0, 3);
  const selectFilter = (category) => { setActiveFilter(category); setShowAll(false); };

  return <section id="projects" className="section-shell section-shell--dark relative overflow-hidden"><div className="absolute left-0 top-20 h-80 w-80 rounded-full bg-cyan-300/15 blur-3xl dark:bg-cyan-500/10" /><div className="section-container relative">
    <motion.div initial={{ y: 30, opacity: 0 }} whileInView={{ y: 0, opacity: 1 }} viewport={{ once: true }} className="mx-auto mb-10 max-w-3xl text-center"><span className="section-kicker">Projects</span><h2 className="section-title text-slate-950 dark:text-slate-50">Featured work with clear outcomes and real traction.</h2><p className="section-copy mx-auto">Real-world solutions that deliver measurable business value</p></motion.div>
    <div className="mb-10 flex flex-wrap justify-center gap-2 sm:gap-3">{categories.map((category) => <button key={category} onClick={() => selectFilter(category)} className={`relative rounded-full px-4 py-2 text-xs font-semibold transition-all sm:px-5 ${activeFilter === category ? 'text-white dark:text-slate-950' : 'glass-card text-slate-600 dark:text-slate-300'}`}>{activeFilter === category && <motion.span layoutId="active-project-filter" className="absolute inset-0 -z-10 rounded-full bg-slate-950 dark:bg-cyan-300" />}{category}</button>)}</div>
    <AnimatePresence mode="wait"><motion.div key={`${activeFilter}-${showAll}`} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="flex flex-col gap-5 pb-5 lg:flex-row lg:gap-5">{visible.map((project, index) => <motion.article key={project.id} initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.07 }} className="group w-full overflow-hidden rounded-[1.75rem] border border-slate-200/70 bg-white/80 shadow-lg backdrop-blur-xl transition-all duration-500 hover:-translate-y-2 hover:shadow-2xl dark:border-slate-800 dark:bg-slate-900/75 lg:w-[calc((100%-2.5rem)/3)]"><div className="relative h-40 overflow-hidden"><img src={project.image} alt={project.title} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/75 to-transparent" /><div className="absolute bottom-3 left-4 right-4 flex justify-between"><Badge className="border-0 bg-cyan-300/90 px-2.5 py-1 text-[10px] font-bold uppercase text-slate-950">{project.category}</Badge>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${project.title}`} className="rounded-full bg-white/90 p-2 text-slate-950"><ExternalLink size={15} /></a>}</div></div><div className="p-5"><p className="mb-2 min-h-8 text-[11px] font-semibold leading-4 text-slate-500 dark:text-slate-400">{project.tagline || 'Selected product build'}</p><h3 className="line-clamp-1 text-xl font-bold text-slate-950 dark:text-white">{project.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{project.solution}</p><div className="mt-4 flex flex-wrap gap-1.5">{project.tech.slice(0, 3).map((tech) => <span key={tech} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-300">{tech}</span>)}{project.tech.length > 3 && <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500 dark:bg-slate-800">+{project.tech.length - 3}</span>}</div><div className="mt-5 flex items-center justify-between border-t border-slate-200 pt-4 dark:border-slate-800"><span className="line-clamp-1 pr-3 text-xs font-semibold text-emerald-600 dark:text-emerald-400">{project.outcome}</span>{project.repoUrl ? <a href={project.repoUrl} target="_blank" rel="noopener noreferrer" aria-label={`View ${project.title} repository`} className="text-slate-500 hover:text-cyan-500"><Github size={18} /></a> : <ArrowRight size={18} className="text-cyan-600 transition-transform group-hover:translate-x-1 dark:text-cyan-300" />}</div></div></motion.article>)}</motion.div></AnimatePresence>
    {filtered.length > 3 && <div className="mt-7 flex justify-center"><button onClick={() => setShowAll((value) => !value)} className="focus-ring inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3 text-sm font-bold text-white shadow-xl transition hover:-translate-y-1 dark:bg-cyan-300 dark:text-slate-950">{showAll ? 'Show fewer projects' : `Show ${filtered.length - 3} other projects`}<ArrowRight size={16} /></button></div>}
  </div></section>;
}
